name: Build
on:
    push:
        branches:
            - master
            - main
        tags:
            - v*
jobs:
    lint-build:
        name: Build
        runs-on: ubuntu-latest

        if: ${{ contains(github.event.head_commit.message, 'build:') }}
        steps:
            - run: echo succeed
