name: Pull Request Check
on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
    lint-pull-request-name:
        name: Pull Request Check
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v4
              with:
                  configFile: ./commitlint.config.js # optional, default is ./commitlint.config.js
