name: Pull Request Commitlint

on:
  pull_request:
      types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
      branches:
        - '**'
jobs:
  pull-request-lint:
    name: PR 확인
    # Only on pull requests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn add @commitlint/config-conventional
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
  commitlint:
    name: master Push or Merge 확인
    # Only if we are pushing or merging PR to the master
    if: (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/master') || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: $
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 30 # Its fine to lint last 30 commits only
      - run: yarn add @commitlint/cli @commitlint/config-conventional
      - uses: wagoid/commitlint-github-action@v2.0.3
        with:
          configFile: ./commitlint.config.js
      - run: yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
