name: Pull Request Commitlint

on:
  pull_request:
      types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
      branches:
        - master
        - main
jobs:
  lint-commits:
    name: PR 확인 확인
    # Only if we are pushing or merging PR to the master
    if: (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/master') || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 30 # Its fine to lint last 30 commits only
      - run: yarn add @commitlint/cli @commitlint/config-conventional
      - uses: wagoid/commitlint-github-action@v2.0.3
        with:
          configFile: ./commitlint.config.js
      - run: yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
