name: Pull Request Check
on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
    lint-pull-request-name:
        name: Pull Request Check
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
          - uses: actions/checkout@v1
          - run: yarn add @commitlint/config-conventional
          - uses: JulienKode/pull-request-name-linter-action@v0.5.0
            with:
              configuration-path: ./commitlint.config.js # optional, default is ./commitlint.config.js
